name: wazo-push-mobile
namespace: official
version: 0.0.2
author: Wazo Team
display_name: Wazo Push Mobile
plugin_format_version: 1
min_wazo_version: 18.13
tags:
  - beta
  - application
homepage: http://www.wazo.io
