name: wazo-push-mobile
namespace: official
version: 0.0.5
author: Wazo Team
display_name: Wazo Push Mobile
plugin_format_version: 1
min_wazo_version: 18.14
tags:
  - beta
  - application
homepage: http://www.wazo.io
debian_depends:
  - python3-pyfcm
